version: '3.3'

services: 
    api:
        build: "."
        ports:
            - "8080"
        environment:
            PORT: 8080
        restart: "always"
        networks: 
            - my-network
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - api
        ports: 
            - "80:80"
        networks: 
            - my-network

#Docker Networks
networks: 
    my-network:
        driver: bridge